### ISSUE TITLE
Changing ports - what has to be done? 

### ISSUE THREAD

**Issue by peteh** [hartmark/sd-rocm#1]
I needed to modify the docker compose file to work on different ports. However I always get connection timeout when trying to generate anything in webui. 

Here is my modified docker-compose file: 

```
services:
  stable-diffusion-comfyui:
    image: rocm/pytorch:latest
    ports:
      - "4000:80"
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.1'
      - 'DOCKER_INSTANCE=comfyui'
    restart: unless-stopped
    command: ["/conf/startup-comfyui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/comfyui:/comfyui
      - ./conf:/conf

  stable-diffusion-webui:
    image: rocm/pytorch:latest
    ports:
      - "4001:81"
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.1'
      - 'DOCKER_INSTANCE=webui'
    restart: unless-stopped
    command: ["/conf/startup-webui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/sd-webui:/sd-webui
      - ./conf:/conf
```

**Comment by peteh** [comment]
Nevermind, the container is crashing because it's incompatible with my gpu.

**Comment by hartmark** [comment]
To change port you need to change the number after :

What GPU do you have?

**Comment by peteh** [comment]
780m onboard gpu with 16gb vram. It works with ollama, that's why I thought it might work here too.

**Comment by hartmark** [comment]
Hmm, it should be supported.

Do you get this error? 
GFX version detection error

**Comment by peteh** [comment]
yaml without version setting results in GFX version detection error
```
services:
  stable-diffusion-comfyui:
    image: rocm/pytorch:latest
    ports:
      - "4000:80"
    environment:
#      - 'HSA_OVERRIDE_GFX_VERSION=11.0.3'
#      - 'PYTORCH_ROCM_ARCH=gfx1100'
#      - 'HSA_OVERRIDE_GFX_VERSION=11.0.2'
      - 'HSA_ENABLE_SDMA=0'
      - 'DOCKER_INSTANCE=comfyui'
    restart: unless-stopped
    command: ["/conf/startup-comfyui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/comfyui:/comfyui
      - ./conf:/conf

  stable-diffusion-webui:
    image: rocm/pytorch:latest
    ports:
      - "4001:81"
    environment:
#      - 'PYTORCH_ROCM_ARCH=gfx1100'
#      - 'HSA_OVERRIDE_GFX_VERSION=11.0.2'
#      - 'HSA_ENABLE_SDMA=0'
      - 'DOCKER_INSTANCE=webui'
    restart: unless-stopped
    command: ["/conf/startup-webui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/sd-webui:/sd-webui
      - ./conf:/conf
```

When I change the overrides for GFX which works for ollama I get other errors when generating the image: 
```yaml
services:
  stable-diffusion-comfyui:
    image: rocm/pytorch:latest
    ports:
      - "4000:80"
    environment:
#      - 'HSA_OVERRIDE_GFX_VERSION=11.0.3'
      - 'PYTORCH_ROCM_ARCH=gfx1100'
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.0'
#      - 'HSA_ENABLE_SDMA=0'
      - 'DOCKER_INSTANCE=comfyui'
    restart: unless-stopped
    command: ["/conf/startup-comfyui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/comfyui:/comfyui
      - ./conf:/conf

  stable-diffusion-webui:
    image: rocm/pytorch:latest
    ports:
      - "4001:81"
    environment:
      - 'PYTORCH_ROCM_ARCH=gfx1100'
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.0'
#      - 'HSA_ENABLE_SDMA=0'
      - 'DOCKER_INSTANCE=webui'
    restart: unless-stopped
    command: ["/conf/startup-webui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/sd-webui:/sd-webui
      - ./conf:/conf
```

When I select FLUX and generate an image the processing starts but then fails in the end

```
pete@homeassistant:~/Programming/sd-rocm$ docker compose up
[+] Running 2/0
 ✔ Container sd-rocm-stable-diffusion-comfyui-1  Recreated                                                                                                                                                                                                                                                                                      0.0s 
 ✔ Container sd-rocm-stable-diffusion-webui-1    Recreated                                                                                                                                                                                                                                                                                      0.0s 
Attaching to stable-diffusion-comfyui-1, stable-diffusion-webui-1
stable-diffusion-comfyui-1  | Docker instance: comfyui
stable-diffusion-comfyui-1  | venv environment already initialized. Skipping initialization steps.
stable-diffusion-comfyui-1  | ====================
stable-diffusion-webui-1    | Docker instance: webui
stable-diffusion-webui-1    | venv environment already initialized. Skipping initialization steps.
stable-diffusion-webui-1    | ====================
stable-diffusion-comfyui-1  | [START] Security scan
stable-diffusion-comfyui-1  | [DONE] Security scan
stable-diffusion-comfyui-1  | ## ComfyUI-Manager: installing dependencies done.
stable-diffusion-comfyui-1  | ** ComfyUI startup time: 2024-08-27 15:51:49.629232
stable-diffusion-comfyui-1  | ** Platform: Linux
stable-diffusion-comfyui-1  | ** Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
stable-diffusion-comfyui-1  | ** Python executable: /root/venv-comfyui/bin/python
stable-diffusion-comfyui-1  | ** ComfyUI Path: /comfyui
stable-diffusion-comfyui-1  | ** Log path: /comfyui/comfyui.log
stable-diffusion-comfyui-1  | 
stable-diffusion-comfyui-1  | Prestartup times for custom nodes:
stable-diffusion-comfyui-1  |    0.3 seconds: /comfyui/custom_nodes/ComfyUI-Manager
stable-diffusion-comfyui-1  | 
stable-diffusion-webui-1    | From https://github.com/lllyasviel/stable-diffusion-webui-forge
stable-diffusion-webui-1    |    0f3309eb..db6448df  main       -> origin/main
stable-diffusion-webui-1    | Updating 0f3309eb..db6448df
stable-diffusion-webui-1    | Fast-forward
stable-diffusion-webui-1    |  README.md                                          |  40 +--
stable-diffusion-webui-1    |  backend/loader.py                                  |  95 ++++--
stable-diffusion-webui-1    |  backend/operations.py                              |  12 +
stable-diffusion-webui-1    |  backend/operations_gguf.py                         |  38 ++-
stable-diffusion-webui-1    |  backend/patcher/lora.py                            |   9 +-
stable-diffusion-webui-1    |  backend/utils.py                                   |  15 +
stable-diffusion-webui-1    |  .../annotator/depth_anything_v2.py                 |  78 +++++
stable-diffusion-webui-1    |  .../forge_legacy_preprocessors/install.py          |   9 +
stable-diffusion-webui-1    |  .../legacy_preprocessors/preprocessor.py           |  17 +
stable-diffusion-webui-1    |  .../legacy_preprocessors/preprocessor_compiled.py  |  16 +
stable-diffusion-webui-1    |  javascript/dragdrop.js                             |  21 +-
stable-diffusion-webui-1    |  modules/api/api.py                                 |   9 +-
stable-diffusion-webui-1    |  modules/api/models.py                              |   4 +-
stable-diffusion-webui-1    |  modules/cmd_args.py                                |   3 +-
stable-diffusion-webui-1    |  modules/extras.py                                  |  13 +-
stable-diffusion-webui-1    |  modules/infotext_utils.py                          |  20 ++
stable-diffusion-webui-1    |  modules/textual_inversion/autocrop.py              | 345 +++++++++++++++++++++
stable-diffusion-webui-1    |  modules/txt2img.py                                 |  15 +-
stable-diffusion-webui-1    |  modules_forge/main_entry.py                        |   4 +-
stable-diffusion-webui-1    |  packages_3rdparty/gguf/quants.py                   | 180 +++++++----
stable-diffusion-webui-1    |  packages_3rdparty/gguf/quick_4bits_ops.py          |  76 +++++
stable-diffusion-webui-1    |  scripts/postprocessing_focal_crop.py               |  56 ++++
stable-diffusion-webui-1    |  22 files changed, 924 insertions(+), 151 deletions(-)
stable-diffusion-webui-1    |  create mode 100644 extensions-builtin/forge_legacy_preprocessors/annotator/depth_anything_v2.py
stable-diffusion-webui-1    |  create mode 100644 modules/textual_inversion/autocrop.py
stable-diffusion-webui-1    |  create mode 100644 packages_3rdparty/gguf/quick_4bits_ops.py
stable-diffusion-webui-1    |  create mode 100644 scripts/postprocessing_focal_crop.py
stable-diffusion-comfyui-1  | Total VRAM 16384 MB, total RAM 47963 MB
stable-diffusion-comfyui-1  | pytorch version: 2.5.0.dev20240822+rocm6.1
stable-diffusion-comfyui-1  | Set vram state to: LOW_VRAM
stable-diffusion-comfyui-1  | Device: cuda:0 AMD Radeon Graphics : native
stable-diffusion-comfyui-1  | Using split optimization for cross attention
stable-diffusion-comfyui-1  | Downloading frontend(Comfy-Org_ComfyUI_frontend) version(1.2.37) to (/comfyui/web_custom_versions/Comfy-Org_ComfyUI_frontend/1.2.37)
stable-diffusion-comfyui-1  | [Prompt Server] web root: /comfyui/web_custom_versions/Comfy-Org_ComfyUI_frontend/1.2.37
stable-diffusion-comfyui-1  | /root/venv-comfyui/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
stable-diffusion-comfyui-1  |   @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
stable-diffusion-comfyui-1  | ### Loading: ComfyUI-Manager (V2.50.2)
stable-diffusion-comfyui-1  | ### ComfyUI Revision: 2610 [7df42b9a] | Released on '2024-08-23'
stable-diffusion-comfyui-1  | 
stable-diffusion-comfyui-1  | Import times for custom nodes:
stable-diffusion-comfyui-1  |    0.0 seconds: /comfyui/custom_nodes/websocket_image_save.py
stable-diffusion-comfyui-1  |    0.0 seconds: /comfyui/custom_nodes/ComfyUI-Manager
stable-diffusion-comfyui-1  | 
stable-diffusion-comfyui-1  | Starting server
stable-diffusion-comfyui-1  | 
stable-diffusion-comfyui-1  | To see the GUI go to: http://0.0.0.0:80
stable-diffusion-comfyui-1  | [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
stable-diffusion-comfyui-1  | [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
stable-diffusion-comfyui-1  | [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
stable-diffusion-comfyui-1  | [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
stable-diffusion-comfyui-1  | [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
stable-diffusion-webui-1    | /sd-webui/modules/infotext_utils.py:19: SyntaxWarning: invalid escape sequence '\('
stable-diffusion-webui-1    |   re_hypernet_hash = re.compile("\(([0-9a-f]+)\)$")
stable-diffusion-webui-1    | Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
stable-diffusion-webui-1    | Version: f2.0.1v1.10.1-previous-450-gdb6448df
stable-diffusion-webui-1    | Commit hash: db6448df744a8929d8ac05d87dec9e85ec8ea48b
stable-diffusion-webui-1    | Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
stable-diffusion-webui-1    | Installing forge_legacy_preprocessor requirement: depth_anything_v2
stable-diffusion-webui-1    | Launching Web UI with arguments: --skip-python-version-check --listen --port 81 --api --precision full --no-half
stable-diffusion-webui-1    | Total VRAM 16384 MB, total RAM 47963 MB
stable-diffusion-webui-1    | pytorch version: 2.5.0.dev20240822+rocm6.1
stable-diffusion-webui-1    | Set vram state to: NORMAL_VRAM
stable-diffusion-webui-1    | Device: cuda:0 AMD Radeon Graphics : native
stable-diffusion-webui-1    | VAE dtype preferences: [torch.float32] -> torch.float32
stable-diffusion-webui-1    | CUDA Using Stream: False
stable-diffusion-webui-1    | Using sub quadratic optimization for cross attention
stable-diffusion-webui-1    | Using split attention for VAE
stable-diffusion-webui-1    | ControlNet preprocessor location: /sd-webui/models/ControlNetPreprocessor
stable-diffusion-webui-1    | 2024-08-27 15:51:57,055 - ControlNet - INFO - ControlNet UI callback registered.
stable-diffusion-webui-1    | Model selected: {'checkpoint_info': {'filename': '/sd-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.safetensors', 'hash': 'a0f13c83'}, 'additional_modules': [], 'unet_storage_dtype': None}
stable-diffusion-webui-1    | Using online LoRAs in FP16: False
stable-diffusion-webui-1    | /root/venv-webui/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
stable-diffusion-webui-1    |   warnings.warn(
stable-diffusion-webui-1    | /sd-webui/modules_forge/patch_basic.py:38: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
stable-diffusion-webui-1    |   result = original_loader(*args, **kwargs)
stable-diffusion-webui-1    | Running on local URL:  http://0.0.0.0:81
stable-diffusion-webui-1    | 
stable-diffusion-webui-1    | To create a public link, set `share=True` in `launch()`.
stable-diffusion-webui-1    | Startup time: 8.4s (prepare environment: 2.8s, import torch: 2.9s, other imports: 0.2s, load scripts: 0.5s, create ui: 1.1s, gradio launch: 0.4s, add APIs: 0.4s).
stable-diffusion-webui-1    | Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
stable-diffusion-webui-1    | [GPU Setting] You will use 93.75% GPU memory (15360.00 MB) to load weights, and use 6.25% GPU memory (1024.00 MB) to do matrix computation.
stable-diffusion-webui-1    | Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': True}
stable-diffusion-webui-1    | [GPU Setting] You will use 93.75% GPU memory (15360.00 MB) to load weights, and use 6.25% GPU memory (1024.00 MB) to do matrix computation.
stable-diffusion-webui-1    | Loading Model: {'checkpoint_info': {'filename': '/sd-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.safetensors', 'hash': 'a0f13c83'}, 'additional_modules': [], 'unet_storage_dtype': None}
stable-diffusion-webui-1    | [Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ...
stable-diffusion-webui-1    | StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
stable-diffusion-webui-1    | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
stable-diffusion-webui-1    | K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
stable-diffusion-webui-1    | Model loaded in 0.4s (unload existing model: 0.2s, forge model load: 0.2s).
stable-diffusion-webui-1    | Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
stable-diffusion-webui-1    | To load target model JointTextEncoder
stable-diffusion-webui-1    | Begin to load 1 model
stable-diffusion-webui-1    | [Unload] Trying to free 1329.14 MB for cuda:0 with 0 models keep loaded ...
stable-diffusion-webui-1    | [Memory Management] Current Free GPU Memory: 9759.90 MB
stable-diffusion-webui-1    | [Memory Management] Required Model Memory: 234.72 MB
stable-diffusion-webui-1    | [Memory Management] Required Inference Memory: 1024.00 MB
stable-diffusion-webui-1    | [Memory Management] Estimated Remaining GPU Memory: 8501.18 MB
stable-diffusion-webui-1    | Moving model(s) has taken 0.06 seconds
stable-diffusion-webui-1    | To load target model KModel
stable-diffusion-webui-1    | Begin to load 1 model
stable-diffusion-webui-1    | [Unload] Trying to free 5457.63 MB for cuda:0 with 0 models keep loaded ...
stable-diffusion-webui-1    | [Unload] Current free memory is 9331.65 MB ... 
stable-diffusion-webui-1    | [Memory Management] Current Free GPU Memory: 9331.65 MB
stable-diffusion-webui-1    | [Memory Management] Required Model Memory: 1639.41 MB
stable-diffusion-webui-1    | [Memory Management] Required Inference Memory: 1024.00 MB
stable-diffusion-webui-1    | [Memory Management] Estimated Remaining GPU Memory: 6668.24 MB
stable-diffusion-webui-1    | Moving model(s) has taken 0.28 seconds
stable-diffusion-webui-1    | 
 60%|██████    | 12/20 [00:21<00:16,  2.06s/it]:0:rocdevice.cpp            :2879: 271933181393 us: [pid:32    tid:0x7f343e3ff700] Callback: Queue 0x7f343c400000 aborting with error : HSA_STATUS_ERROR_INVALID_ISA: The instruction set architecture is invalid. code: 0x100f
stable-diffusion-webui-1    | /conf/startup-webui.sh: line 30:    32 Aborted                 (core dumped) python3 launch.py --skip-python-version-check --listen --port 81 --api --precision full --no-half
```
